### ISSUE TITLE
Add Bitsy to list

### ISSUE THREAD

**Issue by jeremyredhead** [paladin-t/fantasy#27]
Since I noticed that Puzzlescript was listed as a fantasy console, I thought you should also add [Bitsy](https://ledoux.io/bitsy/editor.html) to this list as well.

FC: [Bitsy](https://ledoux.itch.io/bitsy), Adam Ledoux
Language: custom scripting(?)
Price & License: Free, license-less but has a [github repo](https://github.com/le-doux/bitsy)
Platform: Browser
Display: 16x16 sprites which are 8x8 pixels

**Comment by paladin-t** [comment]
Added. Thanks for the information.
