### ISSUE TITLE
I created a fantasy console: LuaG console.

### ISSUE THREAD

**Issue by Vulcalien** [paladin-t/fantasy#35]
It is still under development, but I already created a game using it.
I will add a JavaScript version to run games.
If you consider it valid, I'd like you to add it to the list.

https://github.com/Vulcalien/LuaG-Console

**Comment by paladin-t** [comment]
Just a few quick questions. Does it get any specifications, i.e. screen size, code space size, sprite size, etc. Does it get built-in editors for code, sprite, map or whatever?

**Comment by Vulcalien** [comment]
Screen size: 160x160 (px)
Code space: I decided to put no limit
Sprite size: there can be 256 sprites, each is 8x8.

Built-in editors: at the moment (the console is in beta, v0.5) there is just the map editor.
I am planning to add the sprite editor and the code editor in the next version, sound will come too.

Also, I'd like to create a browser version of it.

**Comment by paladin-t** [comment]
Here we are. Feel free to update it with further progress.

**Comment by Vulcalien** [comment]
Thank you!
I will keep working on It.
