### ISSUE TITLE
Fantasy Computer not on the list: LIMNstation

### ISSUE THREAD

**Issue by DivergentClouds** [paladin-t/fantasy#42]
LIMNstation is a wip fantasy computer i like that is meant to resemble 90s *nix machines. https://github.com/limnarch

Edit: It uses a custom assembly language and a forth-like language called dragonfruit, the price is free, the platform is Love2D, and the resolution is cutomizeable but defaults to 1024x768.

**Comment by paladin-t** [comment]
Hi FlowingLily,

It gets a potential. But it's a little bit early, if I'm not missing anything. I'd be like to add it when it reaches an alpha release, documents and more tiny examples would be nice to have too.

**Comment by FlowingLily** [comment]
Gotcha, yeah, there are some incomplete docs but i only got them thru the fantasy console discord, ill try to remember to bump the issue when its in a more alpha state ^^

**Comment by circutrider21** [comment]
@paladin-t limnstation has came a **really** long way since the last time you checked it, and it even has its own web emulator (powered by emscripten) [here](limnarch.github.io). I think it's finally ready to be on the list

**Comment by paladin-t** [comment]
@circutrider21 Thanks for raising this. Really nice to see the progress, I see there are emu and sdk now. But how am I supposed to upload a compiled program to the web emulator? And where could I find such example programs? Other than that, is there a programming manual which helps me understand and program it?

**Comment by hyenasky** [comment]
I'm the author of LIMNstation and it probably does not belong on this list. The concerns about usability and documentation will probably never be addressed because the project is intended for my own gratification and isn't really supposed to be used by other people. Doing basically anything is very tedious and will stay that way until I make a massive usability effort which I doubt I'll get around to any time soon.

**Comment by paladin-t** [comment]
@hyenasky Thanks for the information.

Closing this for now, feel free to reopen it when the project grows.
