### ISSUE TITLE
Would Petit Computer apply?

### ISSUE THREAD

**Issue by mid-kid** [paladin-t/fantasy#53]
[Petit Computer](https://en.wikipedia.org/wiki/Petit_Computer) is a nintendo-approved (probably the only of its kind) software development application for every nintendo handheld since the DSi. It comes equipped with its own programming language (SmileBASIC), and its own slew of development tools, including a code and graphics editor, a sequencer, and more.
While running on an actual console, this application doesn't tap into its full potential, and comes with its own set of restrictions in order to simplify things so making games on it is _fun_, more than anything.
This might not specifically aim to be a fantasy console but I think given its featureset and restrictions imposed by the environment, I believe it comes dangerously close.

**Comment by paladin-t** [comment]
I added a link of the NS version to the existing SmileBASIC. Since the term "Petit Computer" (プチコン) is mainly used in Japan by SmileBoom for the more common worldwide "SmileBASIC" brand, I prefer to mention it as SmileBASIC, and just keep it as-is for 3DS, NS.

**Comment by mid-kid** [comment]
Oh, sorry, I hadn't seen it on the list. I guess the difference in terms confused me. Thanks for clarifying.
