### ISSUE TITLE
Release date column

### ISSUE THREAD

**Issue by jeremydouglass** [paladin-t/fantasy#54]
It would be helpful to have a release date column -- helpful to know which is recent, and interesting to know which came first.

**Comment by paladin-t** [comment]
Sorry for this replying late. We had a similar discussion before, I don't think this column is relevant enough.

**Comment by jeremydouglass** [comment]
That's fine. Anyone interested in the release information (to the best of my knowledge) can find it here:

https://github.com/jeremydouglass/fantasy/tree/jeremydouglass-release-column
