### ISSUE TITLE
PixelVision8 is now opensource

### ISSUE THREAD

**Issue by youssefsahli** [paladin-t/fantasy#57]
https://pixelvision8.github.io/PixelVision8Website/

The author declared it opensource since some months now.

**Comment by paladin-t** [comment]
Thanks for alerting, updated. I didn't change the pricing info yet, but can't find any price info now. Is it only one free version now?

**Comment by youssefsahli** [comment]
Yes for now. No pricing at all, one free version.

**Comment by paladin-t** [comment]
Done. Closing this.
