### ISSUE TITLE
Add online browser (Webassembly/emscripten) as supported platform to list.

### ISSUE THREAD

**Issue by DartFNM** [paladin-t/fantasy#60]
I think it's important to show that some of consoles can work online in browser too and they have their own online showroom.

Now I know only two of them who support webassembly: TIC-80 and PICO-8. But maybe there are alot of more who may work in browser too.

**Comment by paladin-t** [comment]
By reviewing through the list, I added some supported exporting platforms.
Feel free to supply for any omission.
