### ISSUE TITLE
Not really fantasy consoles

### ISSUE THREAD

**Issue by cosmo0** [paladin-t/fantasy#67]
- CToy: more of a framework, no limitations of display, ram etc.
- ESP LGE: targets real hardware (so, not really "fantasy")
- Nibble: same

They're still interesting projects that have the same goal (rapid prototyping of small simple projects), so I'm not sure they should be completely removed.

**Comment by paladin-t** [comment]
* CToy: remain in the main list, until we collect more similar stuff for a separated list
* ESP LGE, Nibble: I'd prefer to keep it as is, because the hardware is just one of its target, but not must have to run projects

**Comment by cosmo0** [comment]
ok!
