### ISSUE TITLE
Abandoned projects

### ISSUE THREAD

**Issue by cosmo0** [paladin-t/fantasy#68]
There have been a few "dev jam" focusing on fantasy consoles so there are a lot of "one-shot" toy projects in the list.

Maybe there could be two lists? One "active" and one "inactive" projects, so that a person interested in actually using them can focus on the most useable ones?

- 1-bit wonder: an author's comment suggests it was just a toy
- 4BOD: same
- Chroma60: the author has been inactive for several years
- Click4: last updated in 2018
- Drak0: last updated in 2017
- DX8: last updated in 2018
- ECoS: "status: on hold"
- Fazic: last updated march 2020, multiple unanswered issues despite the author being active on other projects
- G-Eon: "no longer in development" (from the project page)
- Homegirl: [project halted][https://poeticandroid.itch.io/homegirl/devlog/142518/happy-birthday-homegirl-and-goodbye)
- Ibniz: the Github is active but the pelulamu.net links are down
- Lowres Coder: replaced by Lowres NX
- Marmmodore-1K: was just a toy for a code jam entry in 2016
- Nano Jammer: last updated in 2018
- Neko8: ["this project is long dead"](https://itch.io/t/632208/error-on-start)
- Phosphor: last updated in 2018
- Pix64: last updated in 2018
- PX8: last updated in 2017
- Riko4: probably inactive: last updated july 2020, author inactive
- Vectorboy: last version in 2017, last blog post in 2018 saying they'll get back to it, then nothing
- VVPet: last updated in 2019
- YukiJS: "alpha project" last updated in 2019

**Comment by kevidryon2** [comment]
Actually... I wanna take the job of developing Homegirl but it's all D... Also imma making my own fantasy console.
I really like to revive dead projects... You know? I fork the source code of some dead fantasy consoles and then continue to update them. So, i'll continue to develop Homegirl... Maybe...

Well... Here goes. It's D. It's 👽.
A wild Lua appeared! It's an 👽 pokémon!
She sells sea 🐚 at the sea shore. The 🐚 she sells are 👽 I'm sure!
Just a bunch of **_wiiiiiiiiiiiiiiiiiiild_** jokes about the languages Homerigl is programmed with.

**Comment by paladin-t** [comment]
* Ibniz: seems moved to http://viznut.fi/ibniz/
* Merged LowRes Coder and NX

Separated main list and jams&experiments. Moved G-eon, Homegirl, NEKO8 to retired.

Didn't change others unless it's sentenced to death by the author, or been widely proved not working or buggy, or not available due to website down etc.

**Comment by cosmo0** [comment]
Thanks that's actually really useful!
