### ISSUE TITLE
Uxn -- portable 8-bit virtual computer

### ISSUE THREAD

**Issue by jan-kleks** [paladin-t/fantasy#70]
Here's a link to their site: https://100r.co/site/uxn.html

Hacker News discussion: https://news.ycombinator.com/item?id=27185950

**Comment by paladin-t** [comment]
I'm impressed by this cute project. But what's holding me up is that it doesn't offer a ready to use assembler yet.

> 
> Uxn is currently under development, we use #uxn on irc.esper.net to coordinate development [07-05-21].

As its site wrote, it is still under active development. So I'd say it's a pending candidate until it makes a more approachable release.

**Comment by neauoire** [comment]
I hadn't realized that this issue was opened, I created a [PR](https://github.com/paladin-t/fantasy/pull/79) yesterday.

There are a couple of assemblers now, there's `asma.rom` that ships with the desktop release, and a couple of others around(forth, c, rust, ocaml, etc)

**Comment by paladin-t** [comment]
merged #79, closing this.
