### ISSUE TITLE
Adding ZZT?

### ISSUE THREAD

**Issue by asiekierka** [paladin-t/fantasy#73]
Okay, this is going to be a tricky one, but I'm going to put together my case. No hard feelings if it doesn't fit the spirit of the list.

ZZT was made in 1991 by Potomac Computer Systems (later Epic MegaGames, even later Epic Games) as an action/puzzle game, but its built-in game creation system with scripting functionality turned out to allow it to be a surprisingly versatile game creation tool. [See: "About ZZT"](https://museumofzzt.com/about-zzt/).

Bitsy and PuzzleScript are on the list. Now, ZZT has been shown to have similar or higher versatility than Bitsy (see, for example, [one of Dr_Dos's modern recommendation lists](https://museumofzzt.com/article/563/the-best-of-zzt-part-2-modern-treasures)) as well as attract a similar audience. While it was originally made as a game, I will admit, its quirky set of limitations (60x25 board size, stat limits, board size limits, unusual scripting language without proper arithmetic, etc.) effectively makes it comparable to a fantasy console in my eyes.

For the formal details:

* Name: ZZT
* Author: Tim Sweeney
* Year: 1991
* URL: https://museumofzzt.com/ (ZZT hasn't had an official website in almost two decades, this is your best bet)
* Language: ZZT-OOP (well... Instructions)
* Price & License: Free, MIT (via a decompilation project but done with the rightsholder's permission, see [The Reconstruction of ZZT](github.com/asiekierka/reconstruction-of-zzt))
* Platform: This is where it gets a bit tricky.
    * ZZT itself targets DOS,
    * [Zeta](https://zeta.asie.pl/) is a tiny emulator dedicated to ZZT which expands that to Windows, Linux, and browsers,
    * There are work-in-progress ports for more obscure platforms (consoles, phones),
    * It is highly recommended to use an external editor tool like [KevEdit](https://museumofzzt.com/zeta/) for greater functionality (Windows, Linux, Mac),
    * While I'm looking into making a native implementation that fixes all of this stuff and combines it into one thing now that the engine is MIT-licensed, the status quo is admittedly a bit tricky.
* Display: 60x25 character mode (plus 20x25 non-user-changeable sidebar on the back, I suppose).

Again, no hard feelings if it doesn't belong - I am curious, however, as I've always seen ZZT as a thing with very similar appeal to a fantasy console. (And, if yes, is its spiritual community-made successor MegaZeux, or is that too close to a general game engine? Hmm...)

**Comment by paladin-t** [comment]
Thank you for the info! I will read and experience more when I get back home.

**Comment by paladin-t** [comment]
Added both ZZT and MegaZeux. They have built-in vm, interpreter, world editors, etc. and have selective limitations. Although it was tagged a game creation system when it originally released, I'd say it's more close to a FC in many aspects than generic game engine for nowadays point of view.

I don't wanna miss gems just due to it came out before the term "Fantasy Console" was widely used.

**Comment by asiekierka** [comment]
One major correction - MegaZeux stopped being maintained for DOS first in the mid-00s; the current mainline targets Windows, Linux, Mac, browser, and a whole ton of other things, with the primary supported library being SDL2.

**Comment by paladin-t** [comment]
Updated.

**Comment by paladin-t** [comment]
Closing this.
