### ISSUE TITLE
Octo not a FC

### ISSUE THREAD

**Issue by kiedtl** [paladin-t/fantasy#74]
[Octo](https://github.com/JohnEarnest/Octo) isn't a fantasy console itself, but rather a suite of development tools (a high-level language, IDE, and debugging utilities) for [CHIP-8](https://en.wikipedia.org/wiki/CHIP-8), which *is* a fantasy console, supposedly the first to be called so.

My suggestion is to replace the Octo link with CHIP-8, linking to its Wikipedia article or perhaps [Awesome CHIP-8](https://chip-8.github.io/links/).

**Comment by paladin-t** [comment]
We had a similar conversation #66, CHIP-8 is listed as a link. Considering CHIP-8 doesn't offer an official release, I prefer to mention it as is, and keep the more approachable implementation (Octo) on the list.

**Comment by kiedtl** [comment]
Hm, yes, there's definitely something to be said for not confusing people who are used to single-implementation fantasy consoles. And Octo is the only web CHIP-8 implementation I'm aware of.

That said, I think displaying the link as "Octo" is misleading at best. Perhaps the link text could be changed to "CHIP-8" but the link to Octo could remain?

**Comment by PureAsbestos** [comment]
Perhaps something like `Octo (CHIP-8)` or `CHIP-8 (Octo)` would do the trick

**Comment by paladin-t** [comment]
Using `Octo (CHIP-8)` now, it's better for any upcoming CHIP-8 compatibles/derivatives in future.
