### ISSUE TITLE
CToy is not an FC

### ISSUE THREAD

**Issue by pudarida** [paladin-t/fantasy#8]
CToy is an interactive and dynamic coding environment and is akin to Love2d rather than a fantasy console, or computer.

**Comment by paladin-t** [comment]
True CToy didn't claim to be an FC itself, but this list doesn't intend to determine an accurate definition about FC. No offense, but CToy is closer to be an FC for quick prototyping, experiment, or just messing some pixels, rather than a generic purpose game engine.
