### ISSUE TITLE
Add TIS-100

### ISSUE THREAD

**Issue by postboy** [paladin-t/fantasy#84]
Maybe we should add [TIS-100](https://en.wikipedia.org/wiki/TIS-100) to the list? This is a game that consists of solving puzzles in assembly language for fantasy computer.

Looks like this game is quite popular and sometimes is used for implementing custom games like [PONG](https://www.reddit.com/r/tis100/comments/39jncd/pong_on_tis100/). This is exactly the reason why it may be an interesting candidate for inclusion in the list.

**Comment by paladin-t** [comment]
Two quick questions:

1. As a user, do I have to complete some story/task mode before I could use the full functional instructions and features?
2. Is there a way that I can share my program with others, or load-and-play others' creations in a convenience way?

**Comment by postboy** [comment]
1. Unfortunately, not exactly. Right from the start, you can write programs that don't involve graphic output. However, you need to get through some levels (until you reach levels where you are expected to draw pixel art) to be able to display something.

2. Yes, programs you write is saved in your save directory. You can add files downloaded from the Internet here, too.

Due to pt. 1 and fruitable discussion in #24, I suppose that TIS-100 is not fantasy-consolish enough for inclusion in the list. Thanks for discussion and for this awesome project, Tony!
