### ISSUE TITLE
New Suggestion: Gamercade

### ISSUE THREAD

**Issue by Xx-Henry-xX** [paladin-t/fantasy#93]
https://gamercade.io/

A fantasy console with big emphasis on online multiplayer w/ rollback netcode.
Haven't tried it myself (as I'm still considering various choices around here) but seems good to me.

**Comment by davipucodigo** [comment]
Pica meu nobre, gostei 👍. Vou dar uma olhada.

**Comment by paladin-t** [comment]
added, thank you for the info.
