### ISSUE TITLE
New suggestion: Game Script

### ISSUE THREAD

**Issue by procedural** [paladin-t/fantasy#94]
https://procedural.itch.io/gamescript

A programming-first C-like fantasy console for Android, PC and Xbox One, available for free for any use, including commercial use.

YouTube playlist with various tutorials for it: https://www.youtube.com/playlist?list=PLvcobyidYcZ05J_4nf90rphKdJ6Wcvr71

Made by Constantine Tarasenkov (me 😄 )

**Comment by paladin-t** [comment]
Maybe I miss something, but how could I get some example programs?

**Comment by paladin-t** [comment]
I'm running a windows version downloaded from itch.io, I pasted the code into game.script, and here's what I got after pressing rerun:
![image](https://github.com/paladin-t/fantasy/assets/2062224/ca845a2e-85be-4f70-b2cb-68e7e1cac481)

BTW, I'm not sure about whether it's DX11 or DX12 of what I've downloaded, here's what I got after double-clicking the exe:
![image](https://github.com/paladin-t/fantasy/assets/2062224/466445e5-af07-474b-9460-0fe4796aae1a)

It's also good to have some example code that gives an overview of the many aspects of your console, i.e. sprites, maps, sounds, or whatever it supports, I think it's quicker than a mandelbrot to give the user a first impression.

**Comment by paladin-t** [comment]
I see. Eventually I succeeded to run the example.
Added.
