### ISSUE TITLE
Please add MEG-4

### ISSUE THREAD

**Issue by bztsrc** [paladin-t/fantasy#95]
Hi,

Could you be please kind to add [MEG-4](https://bztsrc.gitlab.io/meg4/) to your list?

FC: [MEG-4](https://bztsrc.gitlab.io/meg4/) by bzt

Language: [C](https://bztsrc.gitlab.io/meg4/manual_en.html#c), [BASIC](https://bztsrc.gitlab.io/meg4/manual_en.html#basic), [Assembly](https://bztsrc.gitlab.io/meg4/manual_en.html#assembly), [Lua](https://bztsrc.gitlab.io/meg4/manual_en.html#lua)

Price & License: Free and Open Source, [GPLv3+](https://gitlab.com/bztsrc/meg4/-/blob/main/LICENSE)

Platform (Editing; Playing): Windows, Linux, Android, browser, Raspberry Pi, Bare metal

Display: 320 x 200 (scrollable) or 640 x 400 (no scrolling), 256 colors of 32 bit RGBA

A few notes: what makes this fantasy console special is that you can just drag'n'drop files into its window and it Just Works. Supports lots of file formats (png, Amiga MOD, MIDI, Tiled TMX, X11 BDF, FontForge SFD, etc.), and even PICO-8 (both .p8 and .8.png) and TIC-80 (both .tic and .tic.png) cartridges. Both the editor and the player included in a single, dependency-free, portable executable, which is written for web (emscripten), lots of multi-platform libraries (SDL, GLFW, allegro, libretro etc.) as well as for bare metal (disk image creator included). For Raspberry Pi, you can choose between a RaspiOS application and a bare metal version (no OS needed).

Example floppy disks are available on the website, as well as the [MEG-4 User's Manual](https://bztsrc.gitlab.io/meg4/manual_en.html).

Hope you like it! Let me know if you have any questions!
bzt

**Comment by paladin-t** [comment]
Added. Thanks for the info.

**Comment by bztsrc** [comment]
Hi,

Thank you! Could you please add "*Browser*" and "*Bare metal*" to the Platform coloumn? It has an emscripten port too (you can see it on the website), and I've put lot of effort in creating a version that runs without an Operating System.

Thanks,
bzt

**Comment by paladin-t** [comment]
Hello again, updated the Chinese translation. I don't have a gitlab account, so see the following package for your information:

[zh.zip](https://github.com/paladin-t/fantasy/files/12102052/zh.zip)

**Comment by bztsrc** [comment]
Ah, I haven't had the time to check my mails, so I've just noticed this!

Thank you very very much, I've already updated with your fixes and named you as a contributor! Many thanks!
bzt
