### ISSUE TITLE
Missing platforms for MEG-4

### ISSUE THREAD

**Issue by bztsrc** [paladin-t/fantasy#96]
Hi,

First of all, thank you for adding MEG-4 to your list! There's a slight problem though, some of the platforms are missing.
Could you please add "***Browser***" and "***Bare metal***" to the Platform coloumn?

Reasoning: MEG-4 has an [emscripten](https://gitlab.com/bztsrc/meg4/-/tree/main/platform/emscripten) port too (you can see it running on the website), and I've put a lot of effort in creating the other. I call this [bare metal](https://gitlab.com/bztsrc/meg4/-/tree/main/platform/baremetal), because this port produces a disk image without any Operating System (no Windows, no GNU/Linux) that you can yet boot on a desktop PC or run it in a virtual machine like qemu or VirtualBox.

Thanks,
bzt

**Comment by paladin-t** [comment]
Hi,

Thanks for the update. There are two standards that determines whether a platform is listed:

1. for editable, runtime only are not included
2. the column is supposed to contain the ones that have ready-to-use binaries

![图片](https://github.com/paladin-t/fantasy/assets/2062224/977f4066-92c8-49de-8cef-940c93bfad86)

I've tried a few times to load it in browser, but didn't succeed in either Chrome or Firefox. Maybe it's my bad network. I wonder, does the emscripten version offer full functional editors like the desktop ones, if so, I'd be glad to add it.

About the bare metal, I'm not very familar with this sort of distribution. Could you tell me if there is any pre-built binary or a user can only build it from scratch (which does not match the second standard)?

MEG-4 looks great, I'm sure that you've been putting efforts and enthusiasm on this project. Just feel free to correct my misunderstanding.

(One more thing just FYI, the Chinese translation is not very accurate, I can read it, but some of the words are so machine-spoken.)

**Comment by bztsrc** [comment]
Thanks for your answer!

> the column is supposed to contain the ones that have ready-to-use binaries

It does. Besides of the website, you can download it from [meg4-wasm-emscripten.zip](https://gitlab.com/bztsrc/meg4/raw/binaries/meg4-wasm-emscripten.zip) too.

> I've tried a few times to load it in browser, but didn't succeed in either Chrome or Firefox.

Not sure. Nobody reported any issues so far, and it does work for me on several machines. Could you please check the Javascript console to see if there's any related message?

> I wonder, does the emscripten version offer full functional editors like the desktop ones, if so, I'd be glad to add it.

Yes, it does. It's exactly the same as the desktop versions, editor functionality included.

> About the bare metal, I'm not very familar with this sort of distribution.

It generates a similar disk image like the RaspiOS image or any other Linux installer image for example. You flash this to storage, and then you can boot it like any other operating system. It is available for Raspberry Pi as well as for desktop PC.

> Could you tell me if there is any pre-built binary or a user can only build it from scratch (which does not match the second standard)?

I haven't uploaded the binary, because it's big (relatively speaking, ca. 10 Mb). But I can upload it if that's a criteria.

> the Chinese translation is not very accurate, I can read it, but some of the words are so machine-spoken.

Yes, that's Google Translate at its best. I don't speak Chinese myself, but I felt it's important to have a translation. I'd appreciate any corrections, I'd be more than happy to merge any fixes from a native speaker! The dictionary is [here](https://gitlab.com/bztsrc/meg4/-/blob/main/src/lang/zh.h) (simple, single text file, just with quotes. Editable by Notepad).

Cheers,
bzt

**Comment by bztsrc** [comment]
Ok, I've uploaded the binary for the bare metal version too: [meg4-x86_64.iso.tgz](https://gitlab.com/bztsrc/meg4/raw/binaries/meg4-x86_64.iso.tgz). Once unpacked, you'll find the `meg4.iso` file (that is the disk image) and a `run.sh` which will run it in qemu virtual machine. It is using the following command:
```
qemu-system-x86_64 -m 256 -drive file=meg4.iso,format=raw -device virtio-mouse -serial stdio
```

Cheers,
bzt

**Comment by bztsrc** [comment]
So the console's translation is in [zh.h](https://gitlab.com/bztsrc/meg4/-/blob/main/src/lang/zh.h), but I'd really appreciate any help with the website's translation too. It is a single static html file, no magic at all [index.html](https://gitlab.com/bztsrc/meg4/-/blob/main/public/index.html).

Not much really, just a few sentences. Just search for `class="zh"`, for example:
```html
              <a class="nav-link" href="/meg4/">
                <span class="en">Home</span>
                <span class="hu">Főoldal</span>
                <span class="de">Hauptseite</span>
                <span class="fr">Page d'accueil</span>
                <span class="es">Pagina principal</span>
                <span class="ru">Главная страница</span>
                <span class="zh">主页</span>
                <span class="ja">メインページ</span>
              </a>
```
If you're willing to help me fixing the translation, that would be awesome and I would be extremely happy, but please, feel no pressure. It's perfectly okay if you can't help.

Cheers,
bzt

**Comment by bztsrc** [comment]
I've tried to debug your browser issue too. Unfortunately I can't exactly see what the error message is. But this
![wasmerr](https://github.com/paladin-t/fantasy/assets/12779069/d3cd37fd-f85f-4dab-8bc7-4b714d631df3)
suggests that the error is happening in a code that's from ancient times, when Firefox was called NetScape (hence the `NS_...` prefix), so it's very unlikely WebAssembly related, it is much more like a network communication error. Just my two cents.

And I'm sorry, but I can't reproduce the issue either. For me, it is working perfectly, with editors and all, even in Chinese.
![meg4wasm](https://github.com/paladin-t/fantasy/assets/12779069/8666cb30-6162-463a-856b-640ec05bd01e)
I sincerely hope that this screenshot can convince you that it is working in a browser. I'm sorry, this is the best I can offer as proof ATM.

Cheers,
bzt

**Comment by paladin-t** [comment]
Updated the list.

I downloaded the emscripten version and embedded it in an html, it works ok from my local web server. I tried to debug the hosted version, it came with two requests for meg4.wasm, the first one seemed incomplete, and the second one failed due to "socket not connected". I suspect it is caused by cross region networking that is laggy and it just simply cut off timeout requests. Not big deal, just something you might like to know.

![image](https://github.com/paladin-t/fantasy/assets/2062224/cb13b488-c19b-4897-adfb-08bbec4b7b64)

I'd be glad to help improve the Chinese translation, just a little bit off today, I'll let you know when I get some time to proceed.

**Comment by bztsrc** [comment]
> Updated the list.

Thank you!

> I downloaded the emscripten version and embedded it in an html, it works ok from my local web server.

That's great!

> I suspect it is caused by cross region networking that is laggy and it just simply cut off timeout requests.

Yeah, I'm suspecting networking errors too.

> I'd be glad to help improve the Chinese translation, just a little bit off today, I'll let you know when I get some time to proceed.

No pressure! Take your time, we're not in a hurry. I'd be more than happy to merge any fixes, doesn't matter when.

I guess I should close this issue. About the translation it would be the best if you could open a gitlab issue on my repo, because it is unrelated to this one. But it's also okay if you post it here, just mention my name in your post with a '@' and I'll get a notification.

Cheers,
bzt
